<?php

use Illuminate\Database\Seeder;

class StateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('states')->insert(array(
            array('name' => "Andaman and Nicobar Islands"),
            array('name' => "Andhra Pradesh"),
            array('name' => "Arunachal Pradesh"),
            array('name' => "Assam"),
            array('name' => "Bihar"),
            array('name' => "Chandigarh"),
            array('name' => "Chhattisgarh"),
            array('name' => "Dadra and Nagar Haveli"),
            array('name' => "Daman and Diu"),
            array('name' => "Delhi"), 
            array('name' => "Goa"),
            array('name' => "Gujarat"),
            array('name' => "Haryana"),
            array('name' => "Himachal Pradesh"),
            array('name' => "Jammu & Kashmir"),
            array('name' => "Jharkhand"),
            array('name' => "Karnataka"), 
            array('name' => "Kerala"),
            array('name' => "Ladakh"),
            array('name' => "Lakshadweep"),
            array('name' => "Madhya Pradesh"),
            array('name' => "Maharashtra"),
            array('name' => "Manipur"),
            array('name' => "Meghalaya"),
            array('name' => "Mizoram"),
            array('name' => "Nagaland"),  
            array('name' => "Odisha"), 
            array('name' => "Pondicherry"),
            array('name' => "Punjab"),
            array('name' => "Rajasthan"),
            array('name' => "Sikkim"),
            array('name' => "Tamil Nadu"),
            array('name' => "Telangana"),
            array('name' => "Tripura"),
            array('name' => "Uttar Pradesh"),
            array('name' => "Uttarakhand"), 
            array('name' => "West Bengal"),
        )); 



        DB::table('districts')->insert(array(
            array('state_id'=>'1','name'=>'Nicobars'),
            array('state_id'=>'1','name'=>'North and Middle Andaman'),
            array('state_id'=>'1','name'=>'South Andamans'),
            array('state_id'=>'2','name'=>'Anantapur'),
            array('state_id'=>'2','name'=>'Chittoor'),
            array('state_id'=>'2','name'=>'East Godavari'),
            array('state_id'=>'2','name'=>'Guntur'),
            array('state_id'=>'2','name'=>'Krishna'),
            array('state_id'=>'2','name'=>'Kurnool'),
            array('state_id'=>'2','name'=>'Prakasam'),
            array('state_id'=>'2','name'=>'SPSR Nellore'),
            array('state_id'=>'2','name'=>'Srikakulam'),
            array('state_id'=>'2','name'=>'Visakhapatanam'),
            array('state_id'=>'2','name'=>'Vizianagaram'),
            array('state_id'=>'2','name'=>'West Godavari'),
            array('state_id'=>'2','name'=>'Y.S.R.'),
            array('state_id'=>'3','name'=>'Anjaw'),
            array('state_id'=>'3','name'=>'Changlang'),
            array('state_id'=>'3','name'=>'Dibang Valley'),
            array('state_id'=>'3','name'=>'East Kameng'),
            array('state_id'=>'3','name'=>'East Siang'),
            array('state_id'=>'3','name'=>'Kra Daadi'),
            array('state_id'=>'3','name'=>'Kurung Kumey'),
            array('state_id'=>'3','name'=>'Lohit'),
            array('state_id'=>'3','name'=>'Longding'),
            array('state_id'=>'3','name'=>'Lower Dibang Valley'),
            array('state_id'=>'3','name'=>'Lower Subansiri'),
            array('state_id'=>'3','name'=>'Namsai'),
            array('state_id'=>'3','name'=>'Papum Pare'),
            array('state_id'=>'3','name'=>'Siang'),
            array('state_id'=>'3','name'=>'Tawang'),
            array('state_id'=>'3','name'=>'Tirap'),
            array('state_id'=>'3','name'=>'Upper Siang'),
            array('state_id'=>'3','name'=>'Upper Subansiri'),
            array('state_id'=>'3','name'=>'West Kameng'),
            array('state_id'=>'3','name'=>'West Siang'),
            array('state_id'=>'4','name'=>'Baksa'),
            array('state_id'=>'4','name'=>'Barpeta'),
            array('state_id'=>'4','name'=>'Biswanath'),
            array('state_id'=>'4','name'=>'Bongaigaon'),
            array('state_id'=>'4','name'=>'Cachar'),
            array('state_id'=>'4','name'=>'Charaideo'),
            array('state_id'=>'4','name'=>'Chirang'),
            array('state_id'=>'4','name'=>'Darrang'),
            array('state_id'=>'4','name'=>'Dhemaji'),
            array('state_id'=>'4','name'=>'Dhubri'),
            array('state_id'=>'4','name'=>'Dibrugarh'),
            array('state_id'=>'4','name'=>'Dima Hasao'),
            array('state_id'=>'4','name'=>'Goalpara'),
            array('state_id'=>'4','name'=>'Golaghat'),
            array('state_id'=>'4','name'=>'Hailakandi'),
            array('state_id'=>'4','name'=>'Hojai'),
            array('state_id'=>'4','name'=>'Jorhat'),
            array('state_id'=>'4','name'=>'Kamrup Rural'),
            array('state_id'=>'4','name'=>'Kamrup Metro'),
            array('state_id'=>'4','name'=>'Karbi Anglong'),
            array('state_id'=>'4','name'=>'Karimganj'),
            array('state_id'=>'4','name'=>'Kokrajhar'),
            array('state_id'=>'4','name'=>'Lakhimpur'),
            array('state_id'=>'4','name'=>'Majuli'),
            array('state_id'=>'4','name'=>'Marigaon'),
            array('state_id'=>'4','name'=>'Nagaon'),
            array('state_id'=>'4','name'=>'Nalbari'),
            array('state_id'=>'4','name'=>'Sivasagar'),
            array('state_id'=>'4','name'=>'Sonitpur'),
            array('state_id'=>'4','name'=>'South Salmara-Mankachar'),
            array('state_id'=>'4','name'=>'Tinsukia'),
            array('state_id'=>'4','name'=>'Udalguri'),
            array('state_id'=>'4','name'=>'West Karbi Anlong'),
            array('state_id'=>'5','name'=>'Araria'),
            array('state_id'=>'5','name'=>'Arwal'),
            array('state_id'=>'5','name'=>'Aurangabad'),
            array('state_id'=>'5','name'=>'Banka'),
            array('state_id'=>'5','name'=>'Begusarai'),
            array('state_id'=>'5','name'=>'Bhagalpur'),
            array('state_id'=>'5','name'=>'Bhojpur'),
            array('state_id'=>'5','name'=>'Buxar'),
            array('state_id'=>'5','name'=>'Darbhanga'),
            array('state_id'=>'5','name'=>'Gaya'),
            array('state_id'=>'5','name'=>'Gopalganj'),
            array('state_id'=>'5','name'=>'Jamui'),
            array('state_id'=>'5','name'=>'Jehanabad'),
            array('state_id'=>'5','name'=>'Kaimur (BHABUA)'),
            array('state_id'=>'5','name'=>'Katihar'),
            array('state_id'=>'5','name'=>'Khagaria'),
            array('state_id'=>'5','name'=>'Kishanganj'),
            array('state_id'=>'5','name'=>'Lakhisarai'),
            array('state_id'=>'5','name'=>'Madhepura'),
            array('state_id'=>'5','name'=>'Madhubani'),
            array('state_id'=>'5','name'=>'Munger'),
            array('state_id'=>'5','name'=>'Muzaffarpur'),
            array('state_id'=>'5','name'=>'Nalanda'),
            array('state_id'=>'5','name'=>'Nawada'),
            array('state_id'=>'5','name'=>'Pashchim Champaran'),
            array('state_id'=>'5','name'=>'Patna'),
            array('state_id'=>'5','name'=>'Purbi Champaran'),
            array('state_id'=>'5','name'=>'Purnia'),
            array('state_id'=>'5','name'=>'Rohtas'),
            array('state_id'=>'5','name'=>'Saharsa'),
            array('state_id'=>'5','name'=>'Samastipur'),
            array('state_id'=>'5','name'=>'Saran'),
            array('state_id'=>'5','name'=>'Sheikhpura'),
            array('state_id'=>'5','name'=>'Sheohar'),
            array('state_id'=>'5','name'=>'Sitamarhi'),
            array('state_id'=>'5','name'=>'Siwan'),
            array('state_id'=>'5','name'=>'Supaul'),
            array('state_id'=>'5','name'=>'Vaishali'),
            array('state_id'=>'6','name'=>'Chandigarh'),
            array('state_id'=>'7','name'=>'Balod'),
            array('state_id'=>'7','name'=>'Baloda Bazar'),
            array('state_id'=>'7','name'=>'Balrampur'),
            array('state_id'=>'7','name'=>'Bastar'),
            array('state_id'=>'7','name'=>'Bemetara'),
            array('state_id'=>'7','name'=>'Bijapur'),
            array('state_id'=>'7','name'=>'Bilaspur'),
            array('state_id'=>'7','name'=>'Dantewada'),
            array('state_id'=>'7','name'=>'Dhamtari'),
            array('state_id'=>'7','name'=>'Durg'),
            array('state_id'=>'7','name'=>'Gariyaband'),
            array('state_id'=>'7','name'=>'Janjgir-Champa'),
            array('state_id'=>'7','name'=>'Jashpur'),
            array('state_id'=>'7','name'=>'Kabirdham'),
            array('state_id'=>'7','name'=>'Kanker'),
            array('state_id'=>'7','name'=>'Kondagaon'),
            array('state_id'=>'7','name'=>'Korba'),
            array('state_id'=>'7','name'=>'Korea'),
            array('state_id'=>'7','name'=>'Mahasamund'),
            array('state_id'=>'7','name'=>'Mungeli'),
            array('state_id'=>'7','name'=>'Narayanpur'),
            array('state_id'=>'7','name'=>'Raigarh'),
            array('state_id'=>'7','name'=>'Raipur'),
            array('state_id'=>'7','name'=>'Rajnandgaon'),
            array('state_id'=>'7','name'=>'Sukma'),
            array('state_id'=>'7','name'=>'Surajpur'),
            array('state_id'=>'7','name'=>'Surguja'),
            array('state_id'=>'8','name'=>'Dadra AND Nagar Haveli'),
            array('state_id'=>'9','name'=>'Daman'),
            array('state_id'=>'9','name'=>'Diu'),
            array('state_id'=>'10','name'=>'Central'),
            array('state_id'=>'10','name'=>'East'),
            array('state_id'=>'10','name'=>'New Delhi'),
            array('state_id'=>'10','name'=>'North'),
            array('state_id'=>'10','name'=>'North East'),
            array('state_id'=>'10','name'=>'North West'),
            array('state_id'=>'10','name'=>'Shahdara'),
            array('state_id'=>'10','name'=>'South'),
            array('state_id'=>'10','name'=>'South East'),
            array('state_id'=>'10','name'=>'South West'),
            array('state_id'=>'10','name'=>'West'),
            array('state_id'=>'11','name'=>'North GOA'),
            array('state_id'=>'11','name'=>'South GOA'),
            array('state_id'=>'12','name'=>'Ahmadabad'),
            array('state_id'=>'12','name'=>'Amreli'),
            array('state_id'=>'12','name'=>'Anand'),
            array('state_id'=>'12','name'=>'Arvalli'),
            array('state_id'=>'12','name'=>'Banas Kantha'),
            array('state_id'=>'12','name'=>'Bharuch'),
            array('state_id'=>'12','name'=>'Bhavnagar'),
            array('state_id'=>'12','name'=>'Botad'),
            array('state_id'=>'12','name'=>'Chhotaudepur'),
            array('state_id'=>'12','name'=>'Dang'),
            array('state_id'=>'12','name'=>'Devbhumi Dwarka'),
            array('state_id'=>'12','name'=>'Dohad'),
            array('state_id'=>'12','name'=>'Gandhinagar'),
            array('state_id'=>'12','name'=>'Gir Somnath'),
            array('state_id'=>'12','name'=>'Jamnagar'),
            array('state_id'=>'12','name'=>'Junagadh'),
            array('state_id'=>'12','name'=>'Kachchh'),
            array('state_id'=>'12','name'=>'Kheda'),
            array('state_id'=>'12','name'=>'Mahesana'),
            array('state_id'=>'12','name'=>'Mahisagar'),
            array('state_id'=>'12','name'=>'Morbi'),
            array('state_id'=>'12','name'=>'Narmada'),
            array('state_id'=>'12','name'=>'Navsari'),
            array('state_id'=>'12','name'=>'Panch Mahals'),
            array('state_id'=>'12','name'=>'Patan'),
            array('state_id'=>'12','name'=>'Porbandar'),
            array('state_id'=>'12','name'=>'Rajkot'),
            array('state_id'=>'12','name'=>'Sabar Kantha'),
            array('state_id'=>'12','name'=>'Surat'),
            array('state_id'=>'12','name'=>'Surendranagar'),
            array('state_id'=>'12','name'=>'Tapi'),
            array('state_id'=>'12','name'=>'Vadodara'),
            array('state_id'=>'12','name'=>'Valsad'),
            array('state_id'=>'13','name'=>'Ambala'),
            array('state_id'=>'13','name'=>'Bhiwani'),
            array('state_id'=>'13','name'=>'Charki Dadri'),
            array('state_id'=>'13','name'=>'Faridabad'),
            array('state_id'=>'13','name'=>'Fatehabad'),
            array('state_id'=>'13','name'=>'Gurugram'),
            array('state_id'=>'13','name'=>'Hisar'),
            array('state_id'=>'13','name'=>'Jhajjar'),
            array('state_id'=>'13','name'=>'Jind'),
            array('state_id'=>'13','name'=>'Kaithal'),
            array('state_id'=>'13','name'=>'Karnal'),
            array('state_id'=>'13','name'=>'Kurukshetra'),
            array('state_id'=>'13','name'=>'Mahendragarh'),
            array('state_id'=>'13','name'=>'Mewat'),
            array('state_id'=>'13','name'=>'Palwal'),
            array('state_id'=>'13','name'=>'Panchkula'),
            array('state_id'=>'13','name'=>'Panipat'),
            array('state_id'=>'13','name'=>'Rewari'),
            array('state_id'=>'13','name'=>'Rohtak'),
            array('state_id'=>'13','name'=>'Sirsa'),
            array('state_id'=>'13','name'=>'Sonipat'),
            array('state_id'=>'13','name'=>'Yamunanagar'),
            array('state_id'=>'14','name'=>'Bilaspur'),
            array('state_id'=>'14','name'=>'Chamba'),
            array('state_id'=>'14','name'=>'Hamirpur'),
            array('state_id'=>'14','name'=>'Kangra'),
            array('state_id'=>'14','name'=>'Kinnaur'),
            array('state_id'=>'14','name'=>'Kullu'),
            array('state_id'=>'14','name'=>'Lahul AND Spiti'),
            array('state_id'=>'14','name'=>'Mandi'),
            array('state_id'=>'14','name'=>'Shimla'),
            array('state_id'=>'14','name'=>'Sirmaur'),
            array('state_id'=>'14','name'=>'Solan'),
            array('state_id'=>'14','name'=>'UNA'),
            array('state_id'=>'15','name'=>'Anantnag'),
            array('state_id'=>'15','name'=>'Badgam'),
            array('state_id'=>'15','name'=>'Bandipora'),
            array('state_id'=>'15','name'=>'Baramulla'),
            array('state_id'=>'15','name'=>'Doda'),
            array('state_id'=>'15','name'=>'Ganderbal'),
            array('state_id'=>'15','name'=>'Jammu'),
            array('state_id'=>'15','name'=>'Kathua'),
            array('state_id'=>'15','name'=>'Kishtwar'),
            array('state_id'=>'15','name'=>'Kulgam'),
            array('state_id'=>'15','name'=>'Kupwara'),
            array('state_id'=>'19','name'=>'Kargil'),
            array('state_id'=>'19','name'=>'Leh Ladakh'),
            array('state_id'=>'15','name'=>'Poonch'),
            array('state_id'=>'15','name'=>'Pulwama'),
            array('state_id'=>'15','name'=>'Rajauri'),
            array('state_id'=>'15','name'=>'Ramban'),
            array('state_id'=>'15','name'=>'Reasi'),
            array('state_id'=>'15','name'=>'Samba'),
            array('state_id'=>'15','name'=>'Shopian'),
            array('state_id'=>'15','name'=>'Srinagar'),
            array('state_id'=>'15','name'=>'Udhampur'),
            array('state_id'=>'16','name'=>'Bokaro'),
            array('state_id'=>'16','name'=>'Chatra'),
            array('state_id'=>'16','name'=>'Deoghar'),
            array('state_id'=>'16','name'=>'Dhanbad'),
            array('state_id'=>'16','name'=>'Dumka'),
            array('state_id'=>'16','name'=>'East Singhbum'),
            array('state_id'=>'16','name'=>'Garhwa'),
            array('state_id'=>'16','name'=>'Giridih'),
            array('state_id'=>'16','name'=>'Godda'),
            array('state_id'=>'16','name'=>'Gumla'),
            array('state_id'=>'16','name'=>'Hazaribagh'),
            array('state_id'=>'16','name'=>'Jamtara'),
            array('state_id'=>'16','name'=>'Khunti'),
            array('state_id'=>'16','name'=>'Koderma'),
            array('state_id'=>'16','name'=>'Latehar'),
            array('state_id'=>'16','name'=>'Lohardaga'),
            array('state_id'=>'16','name'=>'Pakur'),
            array('state_id'=>'16','name'=>'Palamu'),
            array('state_id'=>'16','name'=>'Ramgarh'),
            array('state_id'=>'16','name'=>'Ranchi'),
            array('state_id'=>'16','name'=>'Sahebganj'),
            array('state_id'=>'16','name'=>'Saraikela Kharsawan'),
            array('state_id'=>'16','name'=>'Simdega'),
            array('state_id'=>'16','name'=>'West Singhbhum'),
            array('state_id'=>'17','name'=>'Bagalkot'),
            array('state_id'=>'17','name'=>'Ballari'),
            array('state_id'=>'17','name'=>'Belagavi'),
            array('state_id'=>'17','name'=>'Bengaluru Rural'),
            array('state_id'=>'17','name'=>'Bengaluru Urban'),
            array('state_id'=>'17','name'=>'Bidar'),
            array('state_id'=>'17','name'=>'Chamarajanagar'),
            array('state_id'=>'17','name'=>'Chikballapur'),
            array('state_id'=>'17','name'=>'Chikkamagaluru'),
            array('state_id'=>'17','name'=>'Chitradurga'),
            array('state_id'=>'17','name'=>'Dakshin Kannad'),
            array('state_id'=>'17','name'=>'Davangere'),
            array('state_id'=>'17','name'=>'Dharwad'),
            array('state_id'=>'17','name'=>'Gadag'),
            array('state_id'=>'17','name'=>'Hassan'),
            array('state_id'=>'17','name'=>'Haveri'),
            array('state_id'=>'17','name'=>'Kalaburagi'),
            array('state_id'=>'17','name'=>'Kodagu'),
            array('state_id'=>'17','name'=>'Kolar'),
            array('state_id'=>'17','name'=>'Koppal'),
            array('state_id'=>'17','name'=>'Mandya'),
            array('state_id'=>'17','name'=>'Mysuru'),
            array('state_id'=>'17','name'=>'Raichur'),
            array('state_id'=>'17','name'=>'Ramanagara'),
            array('state_id'=>'17','name'=>'Shivamogga'),
            array('state_id'=>'17','name'=>'Tumakuru'),
            array('state_id'=>'17','name'=>'Udupi'),
            array('state_id'=>'17','name'=>'Uttar Kannad'),
            array('state_id'=>'17','name'=>'Vijayapura'),
            array('state_id'=>'17','name'=>'Yadgir'),
            array('state_id'=>'18','name'=>'Alappuzha'),
            array('state_id'=>'18','name'=>'Ernakulam'),
            array('state_id'=>'18','name'=>'Idukki'),
            array('state_id'=>'18','name'=>'Kannur'),
            array('state_id'=>'18','name'=>'Kasaragod'),
            array('state_id'=>'18','name'=>'Kollam'),
            array('state_id'=>'18','name'=>'Kottayam'),
            array('state_id'=>'18','name'=>'Kozhikode'),
            array('state_id'=>'18','name'=>'Malappuram'),
            array('state_id'=>'18','name'=>'Palakkad'),
            array('state_id'=>'18','name'=>'Pathanamthitta'),
            array('state_id'=>'18','name'=>'Thiruvananthapuram'),
            array('state_id'=>'18','name'=>'Thrissur'),
            array('state_id'=>'18','name'=>'Wayanad'),
            array('state_id'=>'20','name'=>'Lakshadweep'),
            array('state_id'=>'21','name'=>'Agar Malwa'),
            array('state_id'=>'21','name'=>'Alirajpur'),
            array('state_id'=>'21','name'=>'Anuppur'),
            array('state_id'=>'21','name'=>'Ashoknagar'),
            array('state_id'=>'21','name'=>'Balaghat'),
            array('state_id'=>'21','name'=>'Barwani'),
            array('state_id'=>'21','name'=>'Betul'),
            array('state_id'=>'21','name'=>'Bhind'),
            array('state_id'=>'21','name'=>'Bhopal'),
            array('state_id'=>'21','name'=>'Burhanpur'),
            array('state_id'=>'21','name'=>'Chhatarpur'),
            array('state_id'=>'21','name'=>'Chhindwara'),
            array('state_id'=>'21','name'=>'Damoh'),
            array('state_id'=>'21','name'=>'Datia'),
            array('state_id'=>'21','name'=>'Dewas'),
            array('state_id'=>'21','name'=>'Dhar'),
            array('state_id'=>'21','name'=>'Dindori'),
            array('state_id'=>'21','name'=>'East Nimar'),
            array('state_id'=>'21','name'=>'Guna'),
            array('state_id'=>'21','name'=>'Gwalior'),
            array('state_id'=>'21','name'=>'Harda'),
            array('state_id'=>'21','name'=>'Hoshangabad'),
            array('state_id'=>'21','name'=>'Indore'),
            array('state_id'=>'21','name'=>'Jabalpur'),
            array('state_id'=>'21','name'=>'Jhabua'),
            array('state_id'=>'21','name'=>'Katni'),
            array('state_id'=>'21','name'=>'Khargone'),
            array('state_id'=>'21','name'=>'Mandla'),
            array('state_id'=>'21','name'=>'Mandsaur'),
            array('state_id'=>'21','name'=>'Morena'),
            array('state_id'=>'21','name'=>'Narsinghpur'),
            array('state_id'=>'21','name'=>'Neemuch'),
            array('state_id'=>'21','name'=>'Panna'),
            array('state_id'=>'21','name'=>'Raisen'),
            array('state_id'=>'21','name'=>'Rajgarh'),
            array('state_id'=>'21','name'=>'Ratlam'),
            array('state_id'=>'21','name'=>'Rewa'),
            array('state_id'=>'21','name'=>'Sagar'),
            array('state_id'=>'21','name'=>'Satna'),
            array('state_id'=>'21','name'=>'Sehore'),
            array('state_id'=>'21','name'=>'Seoni'),
            array('state_id'=>'21','name'=>'Shahdol'),
            array('state_id'=>'21','name'=>'Shajapur'),
            array('state_id'=>'21','name'=>'Sheopur'),
            array('state_id'=>'21','name'=>'Shivpuri'),
            array('state_id'=>'21','name'=>'Sidhi'),
            array('state_id'=>'21','name'=>'Singrauli'),
            array('state_id'=>'21','name'=>'Tikamgarh'),
            array('state_id'=>'21','name'=>'Ujjain'),
            array('state_id'=>'21','name'=>'Umaria'),
            array('state_id'=>'21','name'=>'Vidisha'),
            array('state_id'=>'22','name'=>'Ahmednagar'),
            array('state_id'=>'22','name'=>'Akola'),
            array('state_id'=>'22','name'=>'Amravati'),
            array('state_id'=>'22','name'=>'Aurangabad'),
            array('state_id'=>'22','name'=>'Beed'),
            array('state_id'=>'22','name'=>'Bhandara'),
            array('state_id'=>'22','name'=>'Buldhana'),
            array('state_id'=>'22','name'=>'Chandrapur'),
            array('state_id'=>'22','name'=>'Dhule'),
            array('state_id'=>'22','name'=>'Gadchiroli'),
            array('state_id'=>'22','name'=>'Gondia'),
            array('state_id'=>'22','name'=>'Hingoli'),
            array('state_id'=>'22','name'=>'Jalgaon'),
            array('state_id'=>'22','name'=>'Jalna'),
            array('state_id'=>'22','name'=>'Kolhapur'),
            array('state_id'=>'22','name'=>'Latur'),
            array('state_id'=>'22','name'=>'Mumbai'),
            array('state_id'=>'22','name'=>'Mumbai Suburban'),
            array('state_id'=>'22','name'=>'Nagpur'),
            array('state_id'=>'22','name'=>'Nanded'),
            array('state_id'=>'22','name'=>'Nandurbar'),
            array('state_id'=>'22','name'=>'Nashik'),
            array('state_id'=>'22','name'=>'Osmanabad'),
            array('state_id'=>'22','name'=>'Palghar'),
            array('state_id'=>'22','name'=>'Parbhani'),
            array('state_id'=>'22','name'=>'Pune'),
            array('state_id'=>'22','name'=>'Raigad'),
            array('state_id'=>'22','name'=>'Ratnagiri'),
            array('state_id'=>'22','name'=>'Sangli'),
            array('state_id'=>'22','name'=>'Satara'),
            array('state_id'=>'22','name'=>'Sindhudurg'),
            array('state_id'=>'22','name'=>'Solapur'),
            array('state_id'=>'22','name'=>'Thane'),
            array('state_id'=>'22','name'=>'Wardha'),
            array('state_id'=>'22','name'=>'Washim'),
            array('state_id'=>'22','name'=>'Yavatmal'),
            array('state_id'=>'23','name'=>'Bishnupur'),
            array('state_id'=>'23','name'=>'Chandel'),
            array('state_id'=>'23','name'=>'Churachandpur'),
            array('state_id'=>'23','name'=>'Imphal East'),
            array('state_id'=>'23','name'=>'Imphal West'),
            array('state_id'=>'23','name'=>'Senapati'),
            array('state_id'=>'23','name'=>'Tamenglong'),
            array('state_id'=>'23','name'=>'Thoubal'),
            array('state_id'=>'23','name'=>'Ukhrul'),
            array('state_id'=>'24','name'=>'East Garo Hills'),
            array('state_id'=>'24','name'=>'East Jaintia Hills'),
            array('state_id'=>'24','name'=>'East Khasi Hills'),
            array('state_id'=>'24','name'=>'North Garo Hills'),
            array('state_id'=>'24','name'=>'RI Bhoi'),
            array('state_id'=>'24','name'=>'South Garo Hills'),
            array('state_id'=>'24','name'=>'South West Garo Hills'),
            array('state_id'=>'24','name'=>'South West Khasi Hills'),
            array('state_id'=>'24','name'=>'West Garo Hills'),
            array('state_id'=>'24','name'=>'West Jaintia Hills'),
            array('state_id'=>'24','name'=>'West Khasi Hills'),
            array('state_id'=>'25','name'=>'Aizawl'),
            array('state_id'=>'25','name'=>'Champhai'),
            array('state_id'=>'25','name'=>'Kolasib'),
            array('state_id'=>'25','name'=>'Lawngtlai'),
            array('state_id'=>'25','name'=>'Lunglei'),
            array('state_id'=>'25','name'=>'Mamit'),
            array('state_id'=>'25','name'=>'Saiha'),
            array('state_id'=>'25','name'=>'Serchhip'),
            array('state_id'=>'26','name'=>'Dimapur'),
            array('state_id'=>'26','name'=>'Kiphire'),
            array('state_id'=>'26','name'=>'Kohima'),
            array('state_id'=>'26','name'=>'Longleng'),
            array('state_id'=>'26','name'=>'Mokokchung'),
            array('state_id'=>'26','name'=>'Mon'),
            array('state_id'=>'26','name'=>'Peren'),
            array('state_id'=>'26','name'=>'Phek'),
            array('state_id'=>'26','name'=>'Tuensang'),
            array('state_id'=>'26','name'=>'Wokha'),
            array('state_id'=>'26','name'=>'Zunheboto'),
            array('state_id'=>'27','name'=>'Anugul'),
            array('state_id'=>'27','name'=>'Balangir'),
            array('state_id'=>'27','name'=>'Baleshwar'),
            array('state_id'=>'27','name'=>'Bargarh'),
            array('state_id'=>'27','name'=>'Bhadrak'),
            array('state_id'=>'27','name'=>'Boudh'),
            array('state_id'=>'27','name'=>'Cuttack'),
            array('state_id'=>'27','name'=>'Deogarh'),
            array('state_id'=>'27','name'=>'Dhenkanal'),
            array('state_id'=>'27','name'=>'Gajapati'),
            array('state_id'=>'27','name'=>'Ganjam'),
            array('state_id'=>'27','name'=>'Jagatsinghapur'),
            array('state_id'=>'27','name'=>'Jajapur'),
            array('state_id'=>'27','name'=>'Jharsuguda'),
            array('state_id'=>'27','name'=>'Kalahandi'),
            array('state_id'=>'27','name'=>'Kandhamal'),
            array('state_id'=>'27','name'=>'Kendrapara'),
            array('state_id'=>'27','name'=>'Kendujhar'),
            array('state_id'=>'27','name'=>'Khordha'),
            array('state_id'=>'27','name'=>'Koraput'),
            array('state_id'=>'27','name'=>'Malkangiri'),
            array('state_id'=>'27','name'=>'Mayurbhanj'),
            array('state_id'=>'27','name'=>'Nabarangpur'),
            array('state_id'=>'27','name'=>'Nayagarh'),
            array('state_id'=>'27','name'=>'Nuapada'),
            array('state_id'=>'27','name'=>'Puri'),
            array('state_id'=>'27','name'=>'Rayagada'),
            array('state_id'=>'27','name'=>'Sambalpur'),
            array('state_id'=>'27','name'=>'Sonepur'),
            array('state_id'=>'27','name'=>'Sundargarh'),
            array('state_id'=>'28','name'=>'Karaikal'),
            array('state_id'=>'28','name'=>'Mahe'),
            array('state_id'=>'28','name'=>'Pondicherry'),
            array('state_id'=>'28','name'=>'Yanam'),
            array('state_id'=>'29','name'=>'Amritsar'),
            array('state_id'=>'29','name'=>'Barnala'),
            array('state_id'=>'29','name'=>'Bathinda'),
            array('state_id'=>'29','name'=>'Faridkot'),
            array('state_id'=>'29','name'=>'Fatehgarh Sahib'),
            array('state_id'=>'29','name'=>'Fazilka'),
            array('state_id'=>'29','name'=>'Firozepur'),
            array('state_id'=>'29','name'=>'Gurdaspur'),
            array('state_id'=>'29','name'=>'Hoshiarpur'),
            array('state_id'=>'29','name'=>'Jalandhar'),
            array('state_id'=>'29','name'=>'Kapurthala'),
            array('state_id'=>'29','name'=>'Ludhiana'),
            array('state_id'=>'29','name'=>'Mansa'),
            array('state_id'=>'29','name'=>'Moga'),
            array('state_id'=>'29','name'=>'Nawanshahr'),
            array('state_id'=>'29','name'=>'Pathankot'),
            array('state_id'=>'29','name'=>'Patiala'),
            array('state_id'=>'29','name'=>'Rupnagar'),
            array('state_id'=>'29','name'=>'Sangrur'),
            array('state_id'=>'29','name'=>'S.A.S Nagar'),
            array('state_id'=>'29','name'=>'SRI Muktsar Sahib'),
            array('state_id'=>'29','name'=>'Tarn Taran'),
            array('state_id'=>'30','name'=>'Ajmer'),
            array('state_id'=>'30','name'=>'Alwar'),
            array('state_id'=>'30','name'=>'Banswara'),
            array('state_id'=>'30','name'=>'Baran'),
            array('state_id'=>'30','name'=>'Barmer'),
            array('state_id'=>'30','name'=>'Bharatpur'),
            array('state_id'=>'30','name'=>'Bhilwara'),
            array('state_id'=>'30','name'=>'Bikaner'),
            array('state_id'=>'30','name'=>'Bundi'),
            array('state_id'=>'30','name'=>'Chittorgarh'),
            array('state_id'=>'30','name'=>'Churu'),
            array('state_id'=>'30','name'=>'Dausa'),
            array('state_id'=>'30','name'=>'Dholpur'),
            array('state_id'=>'30','name'=>'Dungarpur'),
            array('state_id'=>'30','name'=>'Ganganagar'),
            array('state_id'=>'30','name'=>'Hanumangarh'),
            array('state_id'=>'30','name'=>'Jaipur'),
            array('state_id'=>'30','name'=>'Jaisalmer'),
            array('state_id'=>'30','name'=>'Jalore'),
            array('state_id'=>'30','name'=>'Jhalawar'),
            array('state_id'=>'30','name'=>'Jhunjhunu'),
            array('state_id'=>'30','name'=>'Jodhpur'),
            array('state_id'=>'30','name'=>'Karauli'),
            array('state_id'=>'30','name'=>'Kota'),
            array('state_id'=>'30','name'=>'Nagaur'),
            array('state_id'=>'30','name'=>'Pali'),
            array('state_id'=>'30','name'=>'Pratapgarh'),
            array('state_id'=>'30','name'=>'Rajsamand'),
            array('state_id'=>'30','name'=>'Sawai Madhopur'),
            array('state_id'=>'30','name'=>'Sikar'),
            array('state_id'=>'30','name'=>'Sirohi'),
            array('state_id'=>'30','name'=>'Tonk'),
            array('state_id'=>'30','name'=>'Udaipur'),
            array('state_id'=>'31','name'=>'East District'),
            array('state_id'=>'31','name'=>'North District'),
            array('state_id'=>'31','name'=>'South District'),
            array('state_id'=>'31','name'=>'West District'),
            array('state_id'=>'32','name'=>'Ariyalur'),
            array('state_id'=>'32','name'=>'Chennai'),
            array('state_id'=>'32','name'=>'Coimbatore'),
            array('state_id'=>'32','name'=>'Cuddalore'),
            array('state_id'=>'32','name'=>'Dharmapuri'),
            array('state_id'=>'32','name'=>'Dindigul'),
            array('state_id'=>'32','name'=>'Erode'),
            array('state_id'=>'32','name'=>'Kanchipuram'),
            array('state_id'=>'32','name'=>'Kanniyakumari'),
            array('state_id'=>'32','name'=>'Karur'),
            array('state_id'=>'32','name'=>'Krishnagiri'),
            array('state_id'=>'32','name'=>'Madurai'),
            array('state_id'=>'32','name'=>'Nagapattinam'),
            array('state_id'=>'32','name'=>'Namakkal'),
            array('state_id'=>'32','name'=>'Perambalur'),
            array('state_id'=>'32','name'=>'Pudukkottai'),
            array('state_id'=>'32','name'=>'Ramanathapuram'),
            array('state_id'=>'32','name'=>'Salem'),
            array('state_id'=>'32','name'=>'Sivaganga'),
            array('state_id'=>'32','name'=>'Thanjavur'),
            array('state_id'=>'32','name'=>'Theni'),
            array('state_id'=>'32','name'=>'THE Nilgiris'),
            array('state_id'=>'32','name'=>'Thiruvallur'),
            array('state_id'=>'32','name'=>'Thiruvarur'),
            array('state_id'=>'32','name'=>'Tiruchirappalli'),
            array('state_id'=>'32','name'=>'Tirunelveli'),
            array('state_id'=>'32','name'=>'Tiruppur'),
            array('state_id'=>'32','name'=>'Tiruvannamalai'),
            array('state_id'=>'32','name'=>'Tuticorin'),
            array('state_id'=>'32','name'=>'Vellore'),
            array('state_id'=>'32','name'=>'Villupuram'),
            array('state_id'=>'32','name'=>'Virudhunagar'),
            array('state_id'=>'33','name'=>'Adilabad'),
            array('state_id'=>'33','name'=>'Bhadradri'),
            array('state_id'=>'33','name'=>'Hyderabad'),
            array('state_id'=>'33','name'=>'Jagitial'),
            array('state_id'=>'33','name'=>'Jangoan'),
            array('state_id'=>'33','name'=>'Jayashankar'),
            array('state_id'=>'33','name'=>'Jogulamba'),
            array('state_id'=>'33','name'=>'Kamareddy'),
            array('state_id'=>'33','name'=>'Karimnagar'),
            array('state_id'=>'33','name'=>'Khammam'),
            array('state_id'=>'33','name'=>'Komaram Bheem Asifabad'),
            array('state_id'=>'33','name'=>'Mahabubabad'),
            array('state_id'=>'33','name'=>'Mahbubnagar'),
            array('state_id'=>'33','name'=>'Mancherial'),
            array('state_id'=>'33','name'=>'Medak'),
            array('state_id'=>'33','name'=>'Medchal'),
            array('state_id'=>'33','name'=>'Nagarkurnool'),
            array('state_id'=>'33','name'=>'Nalgonda'),
            array('state_id'=>'33','name'=>'Nirmal'),
            array('state_id'=>'33','name'=>'Nizamabad'),
            array('state_id'=>'33','name'=>'Peddapalli'),
            array('state_id'=>'33','name'=>'Rajanna'),
            array('state_id'=>'33','name'=>'Rangareddi'),
            array('state_id'=>'33','name'=>'Sangareddy'),
            array('state_id'=>'33','name'=>'Siddipet'),
            array('state_id'=>'33','name'=>'Suryapet'),
            array('state_id'=>'33','name'=>'Vikarabad'),
            array('state_id'=>'33','name'=>'Wanaparthy'),
            array('state_id'=>'33','name'=>'Warangal'),
            array('state_id'=>'33','name'=>'Warangal Urban'),
            array('state_id'=>'33','name'=>'Yadadri'),
            array('state_id'=>'34','name'=>'Dhalai'),
            array('state_id'=>'34','name'=>'Gomati'),
            array('state_id'=>'34','name'=>'Khowai'),
            array('state_id'=>'34','name'=>'North Tripura'),
            array('state_id'=>'34','name'=>'Sepahijala'),
            array('state_id'=>'34','name'=>'South Tripura'),
            array('state_id'=>'34','name'=>'Unakoti'),
            array('state_id'=>'34','name'=>'West Tripura'),
            array('state_id'=>'36','name'=>'Almora'),
            array('state_id'=>'36','name'=>'Bageshwar'),
            array('state_id'=>'36','name'=>'Chamoli'),
            array('state_id'=>'36','name'=>'Champawat'),
            array('state_id'=>'36','name'=>'Dehradun'),
            array('state_id'=>'36','name'=>'Haridwar'),
            array('state_id'=>'36','name'=>'Nainital'),
            array('state_id'=>'36','name'=>'Pauri Garhwal'),
            array('state_id'=>'36','name'=>'Pithoragarh'),
            array('state_id'=>'36','name'=>'Rudra Prayag'),
            array('state_id'=>'36','name'=>'Tehri Garhwal'),
            array('state_id'=>'36','name'=>'Udam Singh Nagar'),
            array('state_id'=>'36','name'=>'Uttar Kashi'),
            array('state_id'=>'35','name'=>'Agra'),
            array('state_id'=>'35','name'=>'Aligarh'),
            array('state_id'=>'35','name'=>'Allahabad'),
            array('state_id'=>'35','name'=>'Ambedkar Nagar'),
            array('state_id'=>'35','name'=>'Amethi'),
            array('state_id'=>'35','name'=>'Amroha'),
            array('state_id'=>'35','name'=>'Auraiya'),
            array('state_id'=>'35','name'=>'Azamgarh'),
            array('state_id'=>'35','name'=>'Baghpat'),
            array('state_id'=>'35','name'=>'Bahraich'),
            array('state_id'=>'35','name'=>'Ballia'),
            array('state_id'=>'35','name'=>'Balrampur'),
            array('state_id'=>'35','name'=>'Banda'),
            array('state_id'=>'35','name'=>'Barabanki'),
            array('state_id'=>'35','name'=>'Bareilly'),
            array('state_id'=>'35','name'=>'Basti'),
            array('state_id'=>'35','name'=>'Bhadohi'),
            array('state_id'=>'35','name'=>'Bijnor'),
            array('state_id'=>'35','name'=>'Budaun'),
            array('state_id'=>'35','name'=>'Bulandshahr'),
            array('state_id'=>'35','name'=>'Chandauli'),
            array('state_id'=>'35','name'=>'Chitrakoot'),
            array('state_id'=>'35','name'=>'Deoria'),
            array('state_id'=>'35','name'=>'Etah'),
            array('state_id'=>'35','name'=>'Etawah'),
            array('state_id'=>'35','name'=>'Faizabad'),
            array('state_id'=>'35','name'=>'Farrukhabad'),
            array('state_id'=>'35','name'=>'Fatehpur'),
            array('state_id'=>'35','name'=>'Firozabad'),
            array('state_id'=>'35','name'=>'Gautam Buddha Nagar'),
            array('state_id'=>'35','name'=>'Ghaziabad'),
            array('state_id'=>'35','name'=>'Ghazipur'),
            array('state_id'=>'35','name'=>'Gonda'),
            array('state_id'=>'35','name'=>'Gorakhpur'),
            array('state_id'=>'35','name'=>'Hamirpur'),
            array('state_id'=>'35','name'=>'Hapur'),
            array('state_id'=>'35','name'=>'Hardoi'),
            array('state_id'=>'35','name'=>'Hathras'),
            array('state_id'=>'35','name'=>'Jalaun'),
            array('state_id'=>'35','name'=>'Jaunpur'),
            array('state_id'=>'35','name'=>'Jhansi'),
            array('state_id'=>'35','name'=>'Kannauj'),
            array('state_id'=>'35','name'=>'Kanpur Dehat'),
            array('state_id'=>'35','name'=>'Kanpur Nagar'),
            array('state_id'=>'35','name'=>'Kasganj'),
            array('state_id'=>'35','name'=>'Kaushambi'),
            array('state_id'=>'35','name'=>'Kheri'),
            array('state_id'=>'35','name'=>'Kushi Nagar'),
            array('state_id'=>'35','name'=>'Lalitpur'),
            array('state_id'=>'35','name'=>'Lucknow'),
            array('state_id'=>'35','name'=>'Maharajganj'),
            array('state_id'=>'35','name'=>'Mahoba'),
            array('state_id'=>'35','name'=>'Mainpuri'),
            array('state_id'=>'35','name'=>'Mathura'),
            array('state_id'=>'35','name'=>'Mau'),
            array('state_id'=>'35','name'=>'Meerut'),
            array('state_id'=>'35','name'=>'Mirzapur'),
            array('state_id'=>'35','name'=>'Moradabad'),
            array('state_id'=>'35','name'=>'Muzaffarnagar'),
            array('state_id'=>'35','name'=>'Pilibhit'),
            array('state_id'=>'35','name'=>'Pratapgarh'),
            array('state_id'=>'35','name'=>'Rae Bareli'),
            array('state_id'=>'35','name'=>'Rampur'),
            array('state_id'=>'35','name'=>'Saharanpur'),
            array('state_id'=>'35','name'=>'Sambhal'),
            array('state_id'=>'35','name'=>'Sant Kabeer Nagar'),
            array('state_id'=>'35','name'=>'Shahjahanpur'),
            array('state_id'=>'35','name'=>'Shamli'),
            array('state_id'=>'35','name'=>'Shravasti'),
            array('state_id'=>'35','name'=>'Siddharth Nagar'),
            array('state_id'=>'35','name'=>'Sitapur'),
            array('state_id'=>'35','name'=>'Sonbhadra'),
            array('state_id'=>'35','name'=>'Sultanpur'),
            array('state_id'=>'35','name'=>'Unnao'),
            array('state_id'=>'35','name'=>'Varanasi'),
            array('state_id'=>'37','name'=>'24 Paraganas NORTH'),
            array('state_id'=>'37','name'=>'24 Paraganas SOUTH'),
            array('state_id'=>'37','name'=>'Alipurduar'),
            array('state_id'=>'37','name'=>'Bankura'),
            array('state_id'=>'37','name'=>'Bardhaman'),
            array('state_id'=>'37','name'=>'Birbhum'),
            array('state_id'=>'37','name'=>'Coochbehar'),
            array('state_id'=>'37','name'=>'Darjeeling'),
            array('state_id'=>'37','name'=>'Dinajpur Dakshin'),
            array('state_id'=>'37','name'=>'Dinajpur Uttar'),
            array('state_id'=>'37','name'=>'Hooghly'),
            array('state_id'=>'37','name'=>'Howrah'),
            array('state_id'=>'37','name'=>'Jalpaiguri'),
            array('state_id'=>'37','name'=>'Kolkata'),
            array('state_id'=>'37','name'=>'Maldah'),
            array('state_id'=>'37','name'=>'Medinipur EAST'),
            array('state_id'=>'37','name'=>'Medinipur WEST'),
            array('state_id'=>'37','name'=>'Murshidabad'),
            array('state_id'=>'37','name'=>'Nadia'),
            array('state_id'=>'37','name'=>'Purulia'),
        ));
    }
}
